# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from Node.js LTS Alpine
FROM node:lts-alpine AS builder

# Create app directory
WORKDIR /usr/src/app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci --ignore-scripts && npm run build

# Final image
FROM node:lts-alpine
WORKDIR /usr/src/app

# Copy built files and necessary descriptors
COPY --from=builder /usr/src/app/build ./build
COPY package.json package-lock.json ./

# Install production dependencies
RUN npm ci --omit=dev --ignore-scripts

# Ensure entrypoint is executable
RUN chmod +x build/index.js

# Default command
CMD ["node","build/index.js"]
